sudo: false
language: java
jdk:
    - openjdk8
install:
    - cd codebase
script:
    - ./ant release
notifications:
  email: false
  slack:
    on_success: change
    secure: WaI6XTfSoyeflCD/PrnZge6evjfGF8ogOYdgu5UBl686T80ZorownstrjVApWcIBR73CCS697ij4XTfEC/DS3RkMETrrxFcd6HQy1OLtK9LzJtGHhXRkRyUgJ39QB7FbAYiGfgsveAMV+ZoeeStv6zQSJOr9IzBncB+B8Vzlshc=
